server:
  port: 8888
spring:
  application:
    name: jbusiness-config-server
#  profiles:
#    active:
#    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigoks/jbusiness-config-server-github
          search-paths:
          - 'greeting-service*'
#          default-label: master
#          username: username
#          password: password

